version: "1"

run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: vendor
  issues-exit-code: 1

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Glob‑style paths completely ignored by every linter
  exclude-dirs:
    - vendor
    - build
    - dist
  exclude-files:
    - '.*\.gen\.go'     # protobuf, mockgen, etc.
    - 'mock_.*\.go'      # gomock et al.

  # Ad‑hoc regex suppressions
  exclude:
    - 'Error return value of .*(Close|Write|Flush).* is not checked'

  # Path‑scoped relaxations
  exclude-rules:
    - path: 'api/.*'
      linters: [lll]
    - path: 'internal/.*'
      linters: [dupl, lll]
    - path: 'cmd/.*'
      linters: [gocyclo]
    - path: 'test/.*'
      linters: [errcheck, gocyclo, govet, typecheck]
    - path: '.*_test\.go$'
      linters: [errcheck, typecheck]

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive        # modern replacement for golint
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
    skip-dirs: [test]
  gocognit:
    min-complexity: 15
  lll:
    line-length: 120
    tab-width: 2
  dupl:
    threshold: 100
  misspell:
    locale: US
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/yourorg/yourrepo
  gosec:
    exclude: [G101, G204]
    skip-dirs: [test]
  revive:
    ignore-generated-header: true
    confidence: 0.8
    error-code: 32
    severity: warning
