run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: false              

issues:
  # housekeeping
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

  # generated-code handling

  # global suppressions
  exclude-dirs:              # nothing reported from these folders :contentReference[oaicite:1]{index=1}
    - vendor
    - build
    - dist
    - test
  exclude-files:
    - '.*\.gen\.go'
    - 'mock_.*\.go'
  exclude:
    - 'Error return value of .*(Close|Write|Flush).* is not checked'

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:          
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  lll:
    line-length: 120
    tab-width: 2
  dupl:
    threshold: 100
  misspell:
    locale: US
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/cloud-nimbus/firedoor
  revive:
    confidence: 0.8
    severity: warning