apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"access.cloudnimbus.io/v1alpha1","kind":"Breakglass","metadata":{"annotations":{},"name":"example-breakglass","namespace":"firedoor-system"},"spec":{"accessPolicy":{"rules":[{"actions":["get","list","watch"],"apiGroups":[""],"namespaces":["default"],"resources":["pods"]},{"actions":["get","list"],"apiGroups":[""],"namespaces":["default","kube-system"],"resources":["services"]},{"actions":["get","list","create","update","patch","delete"],"apiGroups":[""],"namespaces":["default"],"resourceNames":["app-config","debug-config"],"resources":["configmaps"]}]},"approvalRequired":false,"duration":"30m","justification":"Emergency access for debugging production issue","subjects":[{"kind":"User","name":"mail@matthewmcleod.co.uk"},{"kind":"Group","name":"developers"}]}}
  creationTimestamp: "2025-07-07T14:41:16Z"
  finalizers:
  - breakglass.firedoor.cloudnimbus.io/finalizer
  generation: 1
  name: example-breakglass
  namespace: firedoor-system
  resourceVersion: "9321"
  uid: 81fa5913-e1a5-4615-9dc9-db94d45a69a6
spec:
  accessPolicy:
    rules:
    - actions:
      - get
      - list
      - watch
      apiGroups:
      - ""
      namespaces:
      - default
      resources:
      - pods
    - actions:
      - get
      - list
      apiGroups:
      - ""
      namespaces:
      - default
      - kube-system
      resources:
      - services
    - actions:
      - get
      - list
      - create
      - update
      - patch
      - delete
      apiGroups:
      - ""
      namespaces:
      - default
      resourceNames:
      - app-config
      - debug-config
      resources:
      - configmaps
  approvalRequired: false
  duration: 30m
  justification: Emergency access for debugging production issue
  subjects:
  - kind: User
    name: mail@matthewmcleod.co.uk
  - kind: Group
    name: developers
status:
  approvedAt: "2025-07-07T14:41:16Z"
  approvedBy: system-auto-approve
  conditions:
  - lastTransitionTime: "2025-07-07T14:41:16Z"
    message: Breakglass access granted to 2 subjects until 2025-07-07T15:11:16Z
    observedGeneration: 1
    reason: AccessGranted
    status: "True"
    type: Approved
  - lastTransitionTime: "2025-07-07T14:41:16Z"
    message: Breakglass access is active until 2025-07-07T15:11:16Z
    observedGeneration: 1
    reason: AccessActive
    status: "True"
    type: Active
  - lastTransitionTime: "2025-07-07T14:41:16Z"
    message: Access has been granted
    observedGeneration: 1
    reason: AccessGranted
    status: "False"
    type: Denied
  expiresAt: "2025-07-07T15:11:16Z"
  grantedAt: "2025-07-07T14:41:16Z"
  phase: Active
