# OpenTelemetry configuration
otel:
  # Enable or disable OpenTelemetry tracing (disabled by default)
  enabled: false
  
  # Exporter type (otlp, stdout, etc.)
  exporter: otlp
  
  # OTLP endpoint for sending traces (pointing to telemetry-system namespace)
  endpoint: http://otel-collector.telemetry-system.svc.cluster.local:4318/v1/traces
  
  # Service name for identifying traces
  service: firedoor-operator 