apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  namespace: monitoring   
  labels:
    grafana_datasource: "1" 
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo             # stable UID; referenced by exemplars
        access: proxy
        url: http://tempo.observability:3100
        basicAuth: false
        isDefault: false       
        jsonData:
          httpMethod: GET
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: 5m
            spanEndTimeShift: 5m
            tags: [{key: job, value: $__input.job}]