# permissions for end users to view breakglasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: firedoor
    app.kubernetes.io/managed-by: kustomize
  name: breakglass-viewer-role
rules:
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses/status
  verbs:
  - get
