---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses/status
  verbs:
  - get
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
