---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
  namespace: firedoor-system
rules:
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses/finalizers
  verbs:
  - update
- apiGroups:
  - access.cloudnimbus.io
  resources:
  - breakglasses/status
  verbs:
  - get
  - patch
  - update
