{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "firedoor.fullname" . }}-manager-role
  labels:
    {{- include "firedoor.labels" . | nindent 4 }}
  annotations:
    {{- include "firedoor.annotations" . | nindent 4 }}
rules:
  # ------------------------------------------------------------------
  # HARD-REQUIRED RULES – do not change unless you know what you're doing
  # ------------------------------------------------------------------
  # Watch & update Breakglass resources
  - apiGroups: [ "access.cloudnimbus.io" ]
    resources: [ "breakglasses" ]
    verbs:     [ "get", "list", "watch", "create", "update", "patch", "delete" ]

  - apiGroups: [ "access.cloudnimbus.io" ]
    resources: [ "breakglasses/status", "breakglasses/finalizers" ]
    verbs:     [ "get", "update", "patch" ]

  # Write Events
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs:     [ "create", "patch" ]

  # Leader election
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs:     [ "get", "list", "watch", "create", "update", "patch", "delete" ]

  # Allow the operator to mint / revoke RBAC objects
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]
    verbs:     [ "get", "list", "watch", "create", "update", "patch", "delete" ]

{{- if .Values.rbac.privilegeEscalation }}
  # ------------------------------------------------------------------
  # PRIVILEGE ESCALATION RULES (enabled when privilegeEscalation: true)
  # ------------------------------------------------------------------
  # Allow the operator to grant permissions it doesn't hold itself
  # This bypasses Kubernetes RBAC restrictions
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]
    verbs:     [ "escalate" ]
{{- end }}

  # ------------------------------------------------------------------
  # USER-CONFIGURABLE EXTRA RULES
  # ------------------------------------------------------------------
{{- range .Values.rbac.extraRules }}
  - apiGroups: {{ toYaml .apiGroups | nindent 4 }}
    resources: {{ toYaml .resources | nindent 4 }}
    verbs: {{ toYaml .verbs | nindent 4 }}
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "firedoor.fullname" . }}-manager-rolebinding
  labels:
    {{- include "firedoor.labels" . | nindent 4 }}
  annotations:
    {{- include "firedoor.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "firedoor.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "firedoor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }} 