{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "firedoor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firedoor.labels" . | nindent 4 }}
  annotations:
    {{- include "firedoor.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }} 