# OpenTelemetry configuration
otel:
  # Enable or disable OpenTelemetry tracing
  enabled: true
  
  # Exporter type (otlp, stdout, etc.)
  exporter: otlp
  
  # OTLP endpoint for sending traces
  endpoint: http://jaeger:14268/api/traces
  
  # Service name for identifying traces
  service: firedoor-operator 