apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: simple-breakglass
  namespace: firedoor-system
spec:
  # Auto-approve for testing
  approvalRequired: false
  
  # Short duration for testing
  duration: 1m
  
  # Justification for the breakglass access
  justification: "Simple test using existing ClusterRoles"
  
  # Subjects who will receive the access
  subjects:
    - kind: User
      name: "test.user@example.com"
  
  # Use existing ClusterRoles instead of custom AccessPolicy
  # This avoids permission issues since these roles already exist
  clusterRoles:
    - "view"  # Read-only access to most resources
    - "edit"  # Read/write access to most resources (except RBAC) 