apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: weekend-maintenance-access
  namespace: firedoor-system
spec:
  justification: "Weekend maintenance access for infrastructure team"
  ticketID: "WEEKEND-7777"
  subjects:
    - kind: Group
      name: "infrastructure-team"
      apiGroup: "rbac.authorization.k8s.io"
  policy:
    - namespace: "default"
      rules:
        - verbs: ["get", "list", "watch"]
          resources: ["pods", "services"]
          apiGroups: [""]
          resourceNames: []
  approval:
    required: true
  schedule:
    start: "2024-06-01T02:00:00Z"
    cron: "0 2 * * 6,0"
    location: "UTC"
    maxActivations: 5
      