apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: clusterrole-breakglass
  namespace: firedoor-system
spec:
  # Duration of the breakglass access
  duration: 1m
  
  # Justification for the breakglass access
  justification: "Emergency cluster access using existing ClusterRoles"
  
  # Subjects who will receive the access
  subjects:
    - kind: User
      name: "admin@example.com"
    - kind: Group
      name: "cluster-admins"
  
  # Use existing ClusterRoles instead of custom AccessPolicy
  clusterRoles:
    - "view"      # Read-only access to most resources
    - "edit"      # Read/write access to most resources
    - "admin"     # Full access within namespaces 