apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: clusterrole-breakglass
  namespace: firedoor-system
spec:
  justification: "Emergency cluster access using existing ClusterRoles"
  ticketID: "CLUSTER-5678"
  duration: "1h"
  
  # Subjects who will receive the access
  subjects:
    - kind: User
      name: "admin@example.com"
      apiGroup: "rbac.authorization.k8s.io"
    - kind: Group
      name: "cluster-admins"
      apiGroup: "rbac.authorization.k8s.io"
  
  # Use existing ClusterRoles instead of custom policy
  clusterRoles:
    - "view"      # Read-only access to most resources
    - "edit"      # Read/write access to most resources
    - "admin"     # Full access within namespaces

  # Approval settings
  approval:
    required: false 