apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: example-breakglass
  namespace: firedoor-system
spec:
  approvalRequired: false
  duration: 30m
  justification: "Emergency access for debugging production issue"
  
  subjects:
    - kind: User
      name: "mail@matthewmcleod.co.uk"
    - kind: Group
      name: "developers"
  
  accessPolicy:
    rules:
      - actions: ["get", "list", "watch"]
        resources: ["pods"]
        apiGroups: [""]
        namespaces: ["default"]
      
      - actions: ["get", "list"]
        resources: ["services"]
        apiGroups: [""]
        namespaces: ["default", "kube-system"]
      
      - actions: ["get", "list", "create", "update", "patch", "delete"]
        resources: ["configmaps"]
        apiGroups: [""]
        namespaces: ["default"]
        resourceNames: ["app-config", "debug-config"]
  