apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: privilege-escalation-example
  namespace: firedoor-system
spec:
  justification: "Privilege escalation for emergency fix"
  ticketID: "ESCALATE-1234"
  subjects:
    - kind: User
      name: "admin@example.com"
      apiGroup: "rbac.authorization.k8s.io"
  clusterRoles:
    - cluster-admin
  approval:
    required: true
  schedule:
    start: "2025-07-16T16:00:00Z"
    end: "2025-07-16T17:00:00Z"
  
  # Policy with permissions the operator might not have itself
  # This will work when privilege escalation is enabled in the operator
  policy:
    # Cluster-scoped resources (no namespace specified)
    - rules:
        # Example: Grant access to nodes (cluster-scoped resource)
        - verbs: ["get", "list", "watch"]
          resources: ["nodes"]
          apiGroups: [""]
          resourceNames: []
        
        # Example: Grant access to persistent volumes
        - verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          resources: ["persistentvolumes"]
          apiGroups: [""]
          resourceNames: []
        
        # Example: Grant access to storage classes
        - verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          resources: ["storageclasses"]
          apiGroups: ["storage.k8s.io"]
          resourceNames: []
        
        # Example: Grant access to custom resources
        - verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          resources: ["customresources"]
          apiGroups: ["custom.example.com"]
          resourceNames: [] 