{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firedoor.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firedoor.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "firedoor.selectorLabels" . | nindent 4 }}
{{- end }} 