apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  namespace: metrics-system   
  labels:
    grafana_datasource: "1" 
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo            
        access: proxy
        url: http://tempo-query-frontend.telemetry-system.svc.cluster.local:3200
        basicAuth: false
        isDefault: false       
        jsonData:
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: 5m
            spanEndTimeShift: 5m
            tags:
              - key: job
                value: $__input.job