apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: namespace-admin-request
  namespace: default
spec:
  # Subject configuration
  user: "developer@example.com"
  
  # Role configuration - namespace-specific role
  role: "admin"  # This will create a RoleBinding in the specified namespace
  
  # Namespace for RoleBinding (not empty for namespace-specific access)
  namespace: "production"  # Access only to the production namespace
  
  # Duration in minutes for how long the access is granted
  durationMinutes: 60  # 1 hour
  
  # Human-readable reason for the access
  reason: "Deploy hotfix to production environment"
  
  # Must be true for the access to be granted
  approved: true 