apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: daily-maintenance-access
  namespace: default
spec:
  # Subjects define who gets access
  subjects:
    - kind: User
      name: "maintenance-team@example.com"
    - kind: Group
      name: "devops-engineers"
  
  # Use existing ClusterRole for maintenance tasks
  clusterRoles:
    - "maintenance-admin"
    - "pod-viewer"
  
  # Approval workflow - no approval needed for scheduled maintenance
  approvalRequired: false
  
  # Duration of each access session
  duration: "2h"
  
  # Required justification
  justification: "Daily system maintenance and health checks - automated recurring access for maintenance team"
  
  # Optional ticket reference
  ticketID: "MAINT-2024-001"
  
  # Enable recurring access
  recurring: true
  
  # Cron schedule: Every weekday at 6 AM UTC
  # Format: "minute hour day-of-month month day-of-week"
  # 0 6 * * 1-5 means: At 6:00 AM, Monday through Friday
  recurrenceSchedule: "0 6 * * 1-5"
---
# Example of a weekly recurring breakglass for security audits
apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: weekly-security-audit
  namespace: security
spec:
  subjects:
    - kind: User
      name: "security-auditor@example.com"
    - kind: Group
      name: "security-team"
  
  # Custom access policy for security audit
  accessPolicy:
    rules:
      - actions: ["get", "list"]
        apiGroups: [""]
        resources: ["pods", "services", "configmaps", "secrets"]
        namespaces: ["production", "staging"]
      - actions: ["get", "list"]
        apiGroups: ["rbac.authorization.k8s.io"]
        resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
      - actions: ["get", "list"]
        apiGroups: ["audit.k8s.io"]
        resources: ["events"]
  
  # Approval required for security audits
  approvalRequired: true
  
  # Duration of audit session
  duration: "4h"
  
  # Justification
  justification: "Weekly security audit and compliance checks - requires manual approval"
  
  # Enable recurring access
  recurring: true
  
  # Cron schedule: Every Monday at 9 AM UTC
  recurrenceSchedule: "0 9 * * 1"
---
# Example of a monthly recurring breakglass for database maintenance
apiVersion: access.cloudnimbus.io/v1alpha1
kind: Breakglass
metadata:
  name: monthly-db-maintenance
  namespace: database
spec:
  subjects:
    - kind: User
      name: "db-admin@example.com"
  
  clusterRoles:
    - "database-admin"
  
  approvalRequired: false
  duration: "6h"
  justification: "Monthly database maintenance, backup verification, and performance optimization"
  ticketID: "DB-MAINT-2024"
  recurring: true
  
  # Cron schedule: First day of every month at 2 AM UTC
  recurrenceSchedule: "0 2 1 * *" 