apiVersion: v1
kind: ConfigMap
metadata:
  name: firedoor-config
  namespace: firedoor-system
data:
  config.yaml: |
    # Firedoor operator configuration
    alertmanager:
      enabled: true
      url: "http://alertmanager.telemetry-system.svc.cluster.local:9093"
      timeout: 30s
      
      # Basic authentication (optional)
      basicAuth:
        username: ""
        password: ""
      
      # TLS configuration (optional)
      tls:
        insecureSkipVerify: false
        caFile: ""
        certFile: ""
        keyFile: ""
      
      # Alert configuration
      alert:
        # Labels to add to all alerts
        labels:
          team: "platform"
          component: "firedoor"
        
        # Annotations to add to all alerts
        annotations:
          runbook_url: "https://wiki.company.com/runbooks/breakglass-access"
        
        # Alert name
        alertName: "BreakglassActive"
        
        # Severity level
        severity: "warning"
        
        # Summary template
        summary: "Breakglass access is active"
        
        # Description template
        description: "A breakglass access request is currently active"
---
# Example Alertmanager configuration for handling breakglass alerts
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: telemetry-system
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname', 'breakglass_name']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'breakglass-team'
      routes:
      - match:
          alertname: BreakglassActive
        receiver: 'breakglass-team'
        group_by: ['breakglass_name', 'breakglass_namespace']
        repeat_interval: 30m  # Repeat every 30 minutes while active
    
    receivers:
    - name: 'breakglass-team'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#platform-alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
    
    templates:
    - '/etc/alertmanager/template/*.tmpl'
    
    inhibit_rules:
    - source_match:
        alertname: BreakglassActive
        status: active
      target_match:
        alertname: BreakglassActive
        status: expired
      equal: ['breakglass_name', 'breakglass_namespace'] 